spring.application.name=donezo-api

server.servlet.context-path=/api
server.port=8080

spring.jackson.property-naming-strategy=SNAKE_CASE

logging.level.org.springframework.web=info
logging.level.org.springframework.http=info

donezo.datasource.jdbc-url=jdbc:postgresql://docker.host.internal:5432/${TODO_DB}
donezo.datasource.username=${POSTGRES_USER}
donezo.datasource.password=${POSTGRES_PWD}
donezo.datasource.pool-size=30

#---
spring.config.activate.on-profile=dev
server.port=8090
logging.level.root=info
logging.level.org.springframework.web=debug
donezo.datasource.jdbc-url=jdbc:postgresql://localhost:10100/${TODO_DB}
donezo.datasource.username=${POSTGRES_USER}
donezo.datasource.password=${POSTGRES_PWD}
donezo.datasource.pool-size=30